default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= Rails.application.credentials.dig(Rails.env.to_sym, :host) %>
  username: <%= Rails.application.credentials.dig(Rails.env.to_sym, :username) %>
  password: <%= Rails.application.credentials.dig(Rails.env.to_sym, :password) %>

development:
  <<: *default
  database: mhrs_development

test:
  <<: *default
  database: mhrs_test

production:
  <<: *default
  database: mhrs_production
  username: mhrs
  password: <%= ENV['MHRS_DATABASE_PASSWORD'] %>
